version: '2'
services:
  php:
    build: data/php
    image: php:7.1
    ports:
      - "9000:9000"
    privileged: true
    volumes:
      - ./app:/var/www/
    tty: true
  # composer:
  #   privileged: true
  #   build: data/composer
  #   image: composer
    # volumes:
    #   - ./app:/app
    #   - /media/Data/Softwares/Desenvolvimento/composer:/composer
  web:
    restart: always
    build: data/nginx
    image: nginx
    ports:
      - "8000:80"
    links:
      - php
    privileged: true
    volumes:
      - ./data/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/
      - ./data/log/nginx:/var/log/nginx
