version: '2'
services:
  php:
    build: data/php
    image: php:7.1
    ports:
      - "9000:9000"
    links:
      - mysql
    privileged: true
    volumes:
      - /var/www/:/var/www/html/
    tty: true
    networks:
      - myapp
  composer:
    privileged: true
    image: composer:1.3
    links:
      - php
    volumes_from:
      - php
    working_dir: /composer
    volumes:
      - /var/www/:/var/www/
      - /usr/lib/composer/:/composer
    networks:
      - myapp
  web:
    restart: always
    build: data/nginx
    image: nginx
    ports:
      - "8000:80"
    links:
      - php
      - mysql
    privileged: true
    volumes:
      - ./data/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/:/var/www/
      - ./data/log/nginx:/var/log/nginx
    networks:
      - myapp
  mysql:
    image: mysql:5.6
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - /etc/profile.d/env_docker
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - myapp
networks:
  myapp:
    driver: bridge

