version: '2'
services:
  php:
    build: data/php-5.6
    image: php:5.6
    ports:
      - "9000:9000"
    privileged: true
    volumes:
      - /var/www/:/var/www/
      - /var/lib/jenkins:/var/jenkins_home
    tty: true
  web1:
    restart: always
    build: data/nginx
    image: nginx:1.10.2
    ports:
      - "8000:80"
      - "8001:80"
    links:
      - php
    privileged: true
    volumes:
      - ./data/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/:/var/www/
      - ./data/log/nginx:/var/log/nginx
  composer:
    privileged: true
#    build: data/composer
    image: composer
    links:
      - php
    volumes_from:
      - php
    working_dir: /composer
    volumes:
      - /var/www/:/var/www/
      - /usr/lib/composer/:/composer
  phpunit:
    image: phpunit/phpunit:5.4.0
    links:
      - php
    volumes:
      - /var/www/:/var/www/
      - /var/lib/jenkins:/var/jenkins_home
  ci:
    build: data/jenkins
    image: jenkins
    ports:
      - "8081:8080"
      - "50001:50000"
    # environment:
      # - JAVA_OPTS="java.util.logging.config.file=/var/jenkins_home/log.properties"
    volumes:
      - /var/lib/jenkins:/var/jenkins_home
