version: '2'
services:
  php:
    build: data/php
    image: php:7.1
    ports:
      - "9000:9000"
    privileged: true
    volumes:
      - /var/www/:/var/www/
    tty: true
  composer:
    privileged: true
    build: data/composer
    image: composer
    links:
      - php
    volumes_from:
      - php
    working_dir: /composer
    volumes:
      - /var/www/:/var/www/
      - /media/Data/Softwares/Desenvolvimento/composer:/composer
  web:
    restart: always
    build: data/nginx
    image: nginx
    ports:
      - "8000:80"
    links:
      - php
    privileged: true
    volumes:
      - ./data/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/:/var/www/
      - ./data/log/nginx:/var/log/nginx
